

import numpy as np
import os
import pandas as pd
from Bio import SeqIO
import re
from pybedtools import BedTool
import os
import io


#
# Definitions
#

configfile: 'config/config.yaml'

samples_df = pd.read_csv(
    config.get("manifest", "config/pedigree.tab"), sep="\t", index_col="SAMPLE"
)

REF_FA = config['REF']


include: "rules/common.smk"
include: "rules/subseq.smk"
include: "rules/msa.smk"
# include: "rules/callable.smk"
# include: "rules/svpop_int.smk"
# include: "rules/combine.smk"









# SET_DEF_NAME = os.path.basename(os.getcwd())

# REGION_BED = '../data/regions/{}/regions.bed'.format(SET_DEF_NAME)


rule all:
    input:
        expand("dn_val/{sample}_valid_table.tsv", sample=samples_df.index),
